# -*- coding: utf-8 -*-
"""task_1_city_region_buildings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGagmGJW3kkhicJfS8cczjyOp_t1ZKTW

# Визуализация. Все здания Советского района города Нижний Новгород.
"""

# установка библиотек
!pip install numpy==1.22.0  
!pip install geopandas mapclassify  
!pip install keplergl  
!pip install osmnx

# импорт библиотек
from keplergl import KeplerGl
import osmnx as ox
# code snippets - enable_custom_widget_manager
# для отображения Kepler в colab
from google.colab import output
output.enable_custom_widget_manager()

# город
CITY_NAME = 'Nizhny Novgorod' # при выводе "Нижний Новгород" на карте отображается только небольшая часть в Канавинском районе
city = ox.geocode_to_gdf(CITY_NAME)
city.explore(tiles="CartoDB positron")

# границы районов
tags = {'admin_level': '9'}
boundaries = ox.geometries_from_polygon(city.unary_union, tags)
boundaries.head()

boundaries.reset_index(inplace=True)
boundaries.head()

# посмотрим границы района
boundaries.explore(tiles="CartoDB positron")

# район города
REGION_NAME = 'Советский район, Нижний Новгород'

region = ox.geocode_to_gdf(REGION_NAME)
region.explore(tiles="CartoDB positron")

# получаем все геометрии по тегу building для района
tags = {'building': True}  
buildings = ox.geometries_from_polygon(region.unary_union, tags)
buildings.head()

buildings.reset_index(inplace=True)
buildings.head()

# покажем на карте Kepler границы города, районов и здания в этом районе
map = KeplerGl(height=500)
map.add_data(data=city.copy(), name='city')# делаем копию из-за того, что метод add_data изменяет геодатафрейм 
map.add_data(data=boundaries.copy(), name='boundaries')  # делаем копию из-за того, что метод add_data изменяет геодатафрейм 
map.add_data(data=buildings.copy(), name='buildings')  # делаем копию из-за того, что метод add_data изменяет геодатафрейм 
map

"""**Вывод**

Получилось визуализировать здания для Советского района Нижнего Новгорода. 

Для нахождения данных о городе Нижний Новгород нужно было использовать название на английском языке, иначе выводились не полные данные.

Внутри границ города вкрапляются какие-то еще другие границы города.

Границы районов выходят за границы города.
"""